import type { DashboardData } from './types';

export const dashboardMock: DashboardData = {
  header: {
    eyebrow: '← Visão geral',
    title: 'Dashboard de Aula',
    subtitle: 'Acompanhe a aula, a frequência dos alunos e os eventos recebidos.',
    actionLabel: 'Iniciar processo',
  },
  courseOverview: {
    title: 'Eletiva II: IoT (Internet das Coisas)',
    subtitle: 'Turma: TADS0043 • Análise e Desenvolvimento de Sistemas',
    dateLabel: 'Dia da aula',
    dateValue: '07/06/2026',
    timeLabel: 'Horário',
    timeValue: '20:00 - 22:00',
    roomLabel: 'Sala',
    roomValue: 'Sala 1604',
    roomIcon: 'building',
    presenceLabel: 'Presença Atual',
    presenceValue: '16 / 20 alunos',
    progress: 80,
    progressNote: '4 alunos ainda sem check-in',
    optionsLabel: 'Mais opções',
  },
  devicePanel: {
    title: 'Dispositivo da Sala 1604',
    description: 'Gerencie os sensores e o fluxo de entrada da sala de aula atual.',
    actions: [
      { label: 'Reiniciar sensor', icon: 'refresh' },
      { label: 'Forçar sincronia', icon: 'sync' },
      { label: 'Encerrar check-in', icon: 'lock', danger: true },
      { label: 'Reabrir manual', icon: 'unlock' },
    ],
  },
  alertsPanel: {
    title: 'Alertas Inteligentes',
    legend: [
      { label: 'Presente', color: '#10B981', icon: 'present' },
      { label: 'Parcial', color: '#F59E0B', icon: 'partial' },
      { label: 'Ausente', color: '#EF4444', icon: 'absent' },
    ],
    alerts: [
      {
        id: 1,
        title: 'Atraso detectado',
        description: 'João Vitor Madeira entrou às 20:25 (após o limite).',
        type: 'warning',
      },
      {
        id: 2,
        title: 'Tentativa suspeita',
        description: 'Múltiplos pings de mesmo ID no dispositivo.',
        type: 'danger',
      },
      {
        id: 3,
        title: 'Frequência geral',
        description: 'Turma abaixo da média histórica (85%).',
        type: 'success',
      },
    ],
  },
  studentList: {
    title: 'Lista em Tempo Real',
    searchPlaceholder: 'Buscar aluno...',
    filterLabel: 'Todos os status',
    filterOptions: ['Todos os status', 'Presente', 'Parcial', 'Ausente'],
    statusLegend: [
      { label: 'Presente', color: '#10B981' },
      { label: 'Parcial', color: '#F59E0B' },
      { label: 'Ausente', color: '#EF4444' },
    ],
    columns: [
      { key: 'name', label: 'Aluno' },
      { key: 'registration', label: 'Matrícula' },
      { key: 'entry', label: 'Entrada' },
      { key: 'permanence', label: 'Permanência' },
      { key: 'status', label: 'Status' },
      { key: 'action', label: 'Ação' },
    ],
    items: [
      {
        id: 1,
        name: 'João Victor Basante',
        avatar: 'https://i.pravatar.cc/150?img=1',
        registration: '2024001',
        entry: '19:55',
        permanence: '1h 20m',
        status: 'Presente',
      },
      {
        id: 2,
        name: 'João Vitor Malveira',
        avatar: 'https://i.pravatar.cc/150?img=2',
        registration: '2024002',
        entry: '20:25',
        permanence: '50m',
        status: 'Parcial',
      },
      {
        id: 3,
        name: 'Maria Clara de Melo',
        avatar: 'https://i.pravatar.cc/150?img=3',
        registration: '2024003',
        entry: '--:--',
        permanence: '0m',
        status: 'Ausente',
      },
      {
        id: 4,
        name: 'Renato Delgado',
        avatar: 'https://i.pravatar.cc/150?img=4',
        registration: '2024004',
        entry: '19:58',
        permanence: '1h 17m',
        status: 'Presente',
      },
      {
        id: 5,
        name: 'Ana Silva Santos',
        avatar: 'https://i.pravatar.cc/150?img=5',
        registration: '2024005',
        entry: '20:02',
        permanence: '1h 10m',
        status: 'Presente',
      },
      {
        id: 6,
        name: 'Carlos Eduardo Oliveira',
        avatar: 'https://i.pravatar.cc/150?img=6',
        registration: '2024006',
        entry: '20:18',
        permanence: '1h 05m',
        status: 'Parcial',
      },
      {
        id: 7,
        name: 'Fernanda Costa Pereira',
        avatar: 'https://i.pravatar.cc/150?img=7',
        registration: '2024007',
        entry: '19:50',
        permanence: '1h 25m',
        status: 'Presente',
      },
      {
        id: 8,
        name: 'Gabriel Martins',
        avatar: 'https://i.pravatar.cc/150?img=8',
        registration: '2024008',
        entry: '--:--',
        permanence: '0m',
        status: 'Ausente',
      },
      {
        id: 9,
        name: 'Helena Rodrigues',
        avatar: 'https://i.pravatar.cc/150?img=9',
        registration: '2024009',
        entry: '20:05',
        permanence: '1h 08m',
        status: 'Presente',
      },
      {
        id: 10,
        name: 'Igor Ferreira Silva',
        avatar: 'https://i.pravatar.cc/150?img=10',
        registration: '2024010',
        entry: '20:30',
        permanence: '45m',
        status: 'Parcial',
      },
      {
        id: 11,
        name: 'Juliana Alves',
        avatar: 'https://i.pravatar.cc/150?img=11',
        registration: '2024011',
        entry: '20:00',
        permanence: '1h 15m',
        status: 'Presente',
      },
      {
        id: 12,
        name: 'Karina Souza Dias',
        avatar: 'https://i.pravatar.cc/150?img=12',
        registration: '2024012',
        entry: '--:--',
        permanence: '0m',
        status: 'Ausente',
      },
      {
        id: 13,
        name: 'Leonardo Gomes',
        avatar: 'https://i.pravatar.cc/150?img=13',
        registration: '2024013',
        entry: '20:08',
        permanence: '1h 12m',
        status: 'Presente',
      },
      {
        id: 14,
        name: 'Marina Teixeira',
        avatar: 'https://i.pravatar.cc/150?img=14',
        registration: '2024014',
        entry: '20:22',
        permanence: '1h 00m',
        status: 'Parcial',
      },
      {
        id: 15,
        name: 'Natália Barros',
        avatar: 'https://i.pravatar.cc/150?img=15',
        registration: '2024015',
        entry: '19:52',
        permanence: '1h 22m',
        status: 'Presente',
      },
      {
        id: 16,
        name: 'Otávio Ribeiro',
        avatar: 'https://i.pravatar.cc/150?img=16',
        registration: '2024016',
        entry: '20:35',
        permanence: '40m',
        status: 'Parcial',
      },
      {
        id: 17,
        name: 'Patricia Nunes',
        avatar: 'https://i.pravatar.cc/150?img=17',
        registration: '2024017',
        entry: '20:03',
        permanence: '1h 11m',
        status: 'Presente',
      },
      {
        id: 18,
        name: 'Quentin Silva Henrique',
        avatar: 'https://i.pravatar.cc/150?img=18',
        registration: '2024018',
        entry: '--:--',
        permanence: '0m',
        status: 'Ausente',
      },
      {
        id: 19,
        name: 'Rafael Santos Souza',
        avatar: 'https://i.pravatar.cc/150?img=19',
        registration: '2024019',
        entry: '20:10',
        permanence: '1h 05m',
        status: 'Presente',
      },
      {
        id: 20,
        name: 'Sofia Monteiro Costa',
        avatar: 'https://i.pravatar.cc/150?img=20',
        registration: '2024020',
        entry: '20:28',
        permanence: '55m',
        status: 'Parcial',
      },
    ],
    totalLabel: 'Mostrando {shown} de {total} alunos',
    previousLabel: 'Anterior',
    nextLabel: 'Próxima',
  },
  presenceChart: {
    title: 'Histórico de presença (mês)',
    legendLabel: 'Linha da turma',
    totalStudents: 20,
    data: [
      { time: 'Aula 1', value: 18 },
      { time: 'Aula 2', value: 19 },
      { time: 'Aula 3', value: 17 },
      { time: 'Aula 4', value: 20 },
      { time: 'Aula 5', value: 16 },
      { time: 'Hoje', value: 16 },
    ],
  },
  auditPanel: {
    title: 'Ações rápidas & Auditoria',
    actionTitle: 'Justificar falta manualmente',
    actionDescription: 'Adicione anexo médico ou atestado para alunos ausentes.',
    actionButtonLabel: 'Iniciar processo',
    logsTitle: 'Últimos logs do sistema',
    logs: [
      { text: 'Sincronização forçada [Sala 1604]', time: '20:35' },
      { text: 'João Victor Malveira deu entrada', time: '20:25' },
      { text: 'Prof. Arnott iniciou a aula', time: '20:00' },
      { text: 'Renato Delgado deu entrada', time: '19:58' },
      { text: 'João Victor Basante deu entrada', time: '19:55' },
    ],
  },
  summaryCards: [
  {
    title: 'Presença Atual',
    value: '87%',
    subtitle: '25 de 29 alunos',
  },
  {
    title: 'Dispositivos IoT',
    value: '12',
    subtitle: 'Todos online',
  },
  {
    title: 'Alertas',
    value: '3',
    subtitle: 'Necessitam atenção',
  },
  ],
};
